InventoryStorage/Models/ErrorViewModel.cs
using System;

namespace InventoryStorage.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InventoryStorage/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryStorage.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Item name")]
        public string ItemName { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public int Location { get; set; }
    }
}

InventoryStorage/Models/ItemHistory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryStorage.Models
{
    public class ItemHistory
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Item name")]
        public string ItemName { get; set; }

        [Required]
        public string Description { get; set; }
        [Required]
        public int Location { get; set; }
        [Required]
        public int OldLocation { get; set; }
       [Required]
        public DateTime DateTimeWhenChanged { get; set; }
    }
}

InventoryStorage/Controllers/HistoryController.cs
using InventoryStorage.Data;
using InventoryStorage.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace InventoryStorage.Controllers
{
    public class HistoryController : Controller
    {

        private readonly ApplicationDbContext _db;
        public HistoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ItemHistory> obj = _db.Histories;
            return View(obj);
        }
        public IActionResult Search(string searchBy, string search)
        {
            if (searchBy == "Id")
            {
                return View(_db.Histories.Where(x => x.Id.ToString().StartsWith(search)).ToList());
            }
            //else if (searchBy == "Description")
            //{
            //    return View(_db.Histories.Where(x => x.Description.ToLower().StartsWith(search)).ToList());
            //}
            //else if (searchBy == "ItemName")
            //{
            //    return View(_db.Histories.Where(x => x.ItemName.ToLower().StartsWith(search)).ToList());
            //}
            return View(_db.Histories.Where(x => x.Location.ToString().StartsWith(search)).ToList());
        }
    }
}

InventoryStorage/Controllers/HomeController.cs
using InventoryStorage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryStorage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InventoryStorage/Controllers/ItemController.cs
using InventoryStorage.Data;
using InventoryStorage.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryStorage.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Item> obj = _db.Items;
            return View(obj);
        }
        //Create GET
        public IActionResult Create()
        {
            return View();
        }
        //Create POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item item)
        {
            if (ModelState.IsValid)
            {
                _db.Items.Add(item);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }
        //Update GET
        public IActionResult Update(int?Id)
        {
            var obj = _db.Items.Find(Id);

            if (obj== null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Update POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Item obj)
        {
            if(obj==null)
            {
                return NotFound();
            }
            _db.Items.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int?Id)
        {
            var obj = _db.Items.Find(Id);

            if (Id==null)
            {
                return NotFound();
            }
            _db.Items.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
       
    }
}

InventoryStorage/Controllers/SearchController.cs
using InventoryStorage.Data;
using InventoryStorage.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace InventoryStorage.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SearchController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Item> obj = _db.Items;
            return View(obj);
        }
       
        public IActionResult Search(string searchBy, string search)
        {
            if (searchBy == "Id")
            {
                return View(_db.Items.Where(x => x.Id.ToString().StartsWith(search)).ToList());
            }
            else if (searchBy == "Description")
            {
                return View(_db.Items.Where(x => x.Description.ToLower().StartsWith(search)).ToList());
            }
            else if (searchBy == "ItemName")
            {
                return View(_db.Items.Where(x => x.ItemName.ToLower().StartsWith(search)).ToList());
            }
            return View(_db.Items.Where(x => x.Location.ToString().StartsWith(search)).ToList());
        }
        public IActionResult Update(int? Id)
        {
            var obj = _db.Items.Find(Id);

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Update POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Item obj)
        {
            if (obj == null)
            {
                return NotFound();
            }
                _db.Items.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
        }
        public IActionResult Delete(int? Id)
        {
            var obj = _db.Items.Find(Id);

            if (Id == null)
            {
                return NotFound();
            }
            _db.Items.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

InventoryStorage/Views/History/Index.cshtml
@model IEnumerable<InventoryStorage.Models.ItemHistory>
@{
    ViewData["Title"] = "История на предмети";
}
<body style="background-color: #FBF8F1; font-family: Verdana, Arial; ">
    <br />
    <br />
    <br />
    <br />
    <h1 class="text-primary">Търсене нa предишно местоположение на предмет</h1>
    <div class="container p-3">
        <form method="post" asp-controller="History" asp-action="Search">
            <div class="row">
                <div class="col-12">
                    <b>Търсене по:</b>
                    @Html.RadioButton("searchBy", "Id", true)  Номер
                    @Html.RadioButton("searchBy", "Location")  Сегашна локация
                    <div class=" form-group row">
                        <input type="search" name="search" />

                    </div>
                    <div class="form-group row">
                        <input type="submit" value="Търсене" class="btn m-1" style="background-color: #24A19C;color:whitesmoke;" asp-controller="History" asp-action="Search" />
                    </div>
                </div>
            </div>
        </form>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered borthead-dark table-striped table-hover" style="width:100%;
                background-color: aliceblue">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Име</th>
                        <th>Описание</th>
                        <th>Сегашно местоположение</th>
                        <th>Предишно местоположение</th>
                        <th>Дата на преместване</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width="10%">@item.Id</td>
                            <td width="18%">@item.ItemName</td>
                            <td width="18%">@item.Description</td>
                            <td width="12%">@item.Location</td>
                            <td width="10%">@item.OldLocation</td>
                            <td width="15%">@item.DateTimeWhenChanged</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Няма въведени предмети!</p>
        }
    </div>
</body>

InventoryStorage/Views/History/Search.cshtml
@model IEnumerable<InventoryStorage.Models.ItemHistory>
@{
        ViewData["Title"] = "Търсене на предмет по номер";
    }
<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <h1>Търсене на предмет</h1>
    <div class="container p-3">
        <form method="post" asp-controller="History" asp-action="Search">
            <div class="row">
                <div class="col-12">
                    <b>Търсене по:</b>
                    @Html.RadioButton("searchBy", "Id", true)  Номер
                    @Html.RadioButton("searchBy", "ItemName")  Име
                    @Html.RadioButton("searchBy", "Description")  Описание
                    <div class=" form-group row">
                        <input type="search" name="search" />
                    </div>
                    <div class="form-group row">
                        <input type="submit" value="Търсене"class="btn m-1" style="background-color: #24A19C;color:whitesmoke;" asp-controller="History" asp-action="Search" />
                    </div>
                </div>
            </div>
        </form>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered borthead-dark table-striped table-hover" style="width:100%;
                background-color: aliceblue">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Име</th>
                        <th>Описание</th>
                        <th>Сегашно местоположение</th>
                        <th>Предишно местоположение</th>
                        <th>Дата на преместване</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width="10%">@item.Id</td>
                            <td width="18%">@item.ItemName</td>
                            <td width="18%">@item.Description</td>
                            <td width="12%">@item.Location</td>
                            <td width="10%">@item.OldLocation</td>
                            <td width="15%">@item.DateTimeWhenChanged</td>
                        </tr>
                    }
                </tbody>
            </table> }
        else
        {
            <p>Няма въведени предмети!</p>}
    </div>
</body>

InventoryStorage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Начало";
}
<!DOCTYPE html>
<body>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <div class="bg-image"> </div>
    <div class="bg-text">
        <h1 style="font-size:30px;font-weight:bold">
            Това приложение има за цел да се подобри организацията и
            проследяването на предмети в училище.
        </h1>
        <h2>
            Създават се предмети с описание,местоположение,име и уникален номер, по които могат да бъдат извършвани различни операции
            като търсене, смяна на местоположение и проверяване на предишно местоположение.
        </h2>
    </div>
</body>

InventoryStorage/Views/Item/Create.cshtml
@model InventoryStorage.Models.Item
@{ 
    ViewData["Title"] = "Създаване на нов предмет";
}
<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <h1>Създаване на нов предмет</h1>
    <form method="post" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-12">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class=" form-group row">
                    <label class="col-2 m-1 form-control" asp-for="Id">Номер</label>
                    <label class="col-3 m-1 form-control" asp-for="ItemName">Име</label>
                    <label class="col-3 m-1 form-control" asp-for="Description">Описание</label>
                    <label class="col-3 m-1 form-control" asp-for="Location">Местоположение</label>
                </div>
                <div class=" form-group row">
                    <input disabled class="col-2  form-control m-1" asp-for="Id" />
                    <input class="col-3  form-control m-1" asp-for="ItemName" />
                    <input class="col-3  form-control m-1" asp-for="Description" />
                    <input class="col-3  form-control m-1" asp-for="Location" />
                </div>
                <div class=" form-group row">
                    <button type="submit" class="col-3 btn btn-success m-1">Запазване</button>
                    <button asp-action="Index" class="col-3 btn btn-danger m-1">Назад</button>
                </div>
            </div>
        </div>
    </form>
</body>

InventoryStorage/Views/Item/Index.cshtml
@model IEnumerable<InventoryStorage.Models.Item>

<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col pt-6">
                <h2 class="text-primary">
                    Списък с предмети
                </h2>
            </div>
        </div>
        <br />
        <div class="col-6 text-right" style="float: right;">
            <a class="btn w-55" asp-controller="Item" asp-action="Create" style="background-color: #24A19C;color:whitesmoke;">Създаване на нов предмет</a>
        </div>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered borthead-dark table-striped table-hover" style="width:100%;
                background-color: aliceblue">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Име</th>
                        <th>Описание</th>
                        <th>Местоположение</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width="10%">@item.Id</td>
                            <td width="24%">@item.ItemName</td>
                            <td width="24%">@item.Description</td>
                            <td width="14%">@item.Location</td>
                            <td width="24%">
                                <a class="btn btn-success m-1" asp-controller="Item" asp-action="Update" asp-route-id=@item.Id>Промяна</a>
                                <a class="btn btn-danger m-1" asp-controller="Item" asp-action="Delete" asp-route-id=@item.Id>Изтриване</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Няма въведени предмети!</p>
        }
    </div>
</body>

InventoryStorage/Views/Item/Update.cshtml
@model InventoryStorage.Models.Item
@{
    ViewData["Title"] = "Създаване на нов предмет";
}
<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <h1>Смяна на местоположението на предмета</h1>
    <form method="post" asp-action="Update">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-12">

                <div class=" form-group row">
                    <label class="col-2 m-1 form-control" asp-for="Id">Номер</label>
                    <label class="col-3 m-1 form-control" asp-for="ItemName">Име</label>
                    <label class="col-3 m-1 form-control" asp-for="Description">Описание</label>
                    <label class="col-3 m-1 form-control" asp-for="Location">Местоположение</label>
                </div>
                <div class=" form-group row">
                    <input class="col-2  form-control m-1" asp-for="Id" disabled />
                    <input class="col-3  form-control m-1" asp-for="ItemName" />
                    <input class="col-3  form-control m-1" asp-for="Description" />
                    <input class="col-3  form-control m-1" asp-for="Location" />
                </div>
                <div class=" form-group row">
                    <button type="submit" class="col-3 btn btn-success m-1">Запазване</button>
                    <button asp-action="Index" class="col-3 btn btn-danger m-1">Назад</button>
                </div>
            </div>
        </div>
    </form>
</body>

InventoryStorage/Views/Search/Index.cshtml
@model IEnumerable<InventoryStorage.Models.Item>
@{
        ViewData["Title"] = "Търсене на предмет";
    }
<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <h1 class="text-primary">Търсене на предмет</h1>
    <div class="container p-3">
        <form method="post" asp-controller="Search" asp-action="Search">
            <div class="row">
                <div class="col-12">
                    <b>Търсене по:</b>
                    
                    @Html.RadioButton("searchBy", "Id", true)  Номер
                    @Html.RadioButton("searchBy", "ItemName")  Име
                    @Html.RadioButton("searchBy", "Description")  Описание
                    @Html.RadioButton("searchBy", "Location")  Местоположение
                    
                    <div class=" form-group row">
                        <input type="search" name="search" />

                    </div>
                    <div class="form-group row">
                        <input type="submit" value="Търсене" class="btn m-1" style="background-color: #24A19C;color:whitesmoke;" asp-controller="Search" asp-action="Search" />
                    </div>
                </div>
            </div>
        </form>
        @if (Model.Count() > 0)
        {
    <table class="table table-bordered borthead-dark table-striped table-hover" style="width:100%;
                background-color: aliceblue">
        <thead>
            <tr>
                <th>Номер</th>
                <th>Име</th>
                <th>Описание</th>
                <th>Местоположение</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="10%">@item.Id</td>
                    <td width="24%">@item.ItemName</td>
                    <td width="24%">@item.Description</td>
                    <td width="14%">@item.Location</td>
                    <td width="24%">
                        <a class="btn btn-success m-1" asp-controller="Search" asp-action="Update" asp-route-id=@item.Id>Промяна</a>
                        <a class="btn btn-danger m-1" asp-controller="Search" asp-action="Delete" asp-route-id=@item.Id>Изтриване</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
        }
        else
        {
            <p>Няма въведени предмети!</p>
        }
    </div>
</body>

InventoryStorage/Views/Search/Search.cshtml
@model IEnumerable<InventoryStorage.Models.Item>
@{
        ViewData["Title"] = "Търсене на предмет по номер";
    }
<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <h1>Търсене на предмет</h1>
    <div class="container p-3">
        <form method="post" asp-controller="Search" asp-action="Search">
            <div class="row">
                <div class="col-12">
                    <b>Търсене по:</b>
                    @Html.RadioButton("searchBy", "Id", true)  Номер
                    @Html.RadioButton("searchBy", "ItemName")  Име
                    @Html.RadioButton("searchBy", "Description")  Описание
                    @Html.RadioButton("searchBy", "Location")  Местоположение
                    <div class=" form-group row">
                        <input type="search" name="search" />
                    </div>
                    <div class="form-group row">
                        <input type="submit" value="Търсене" class="btn m-1" style="background-color: #24A19C;color:whitesmoke;" asp-controller="Search" asp-action="Search" />
                    </div>
                </div>
            </div>
        </form>
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered borthead-dark table-striped table-hover" style="width:100%;
                background-color: aliceblue">
                <thead>
                    <tr>
                        <th>Номер</th>
                        <th>Име</th>
                        <th>Описание</th>
                        <th>Местоположение</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width="10%">@item.Id</td>
                            <td width="24%">@item.ItemName</td>
                            <td width="24%">@item.Description</td>
                            <td width="14%">@item.Location</td>
                            <td width="24%">
                                <a class="btn btn-success m-1" asp-controller="Search" asp-action="Update" asp-route-id=@item.Id>Промяна</a>
                                <a class="btn btn-danger m-1" asp-controller="Search" asp-action="Delete" asp-route-id=@item.Id>Изтриване</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Няма въведени предмети!</p>
        }
    </div>
</body>

InventoryStorage/Views/Search/Update.cshtml
@model InventoryStorage.Models.Item
@{
    ViewData["Title"] = "Смяна на местоположението на предмета";
}
<body style="background-color: #FBF8F1; font-family: Verdana, Arial;">
    <br />
    <br />
    <br />
    <br />
    <h1>Смяна на местоположението на предмета</h1>
    <form method="post" asp-action="Update">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-12">

                <div class=" form-group row">
                    <label class="col-2 m-1 form-control" asp-for="Id">Номер</label>
                    <label class="col-3 m-1 form-control" asp-for="ItemName">Име</label>
                    <label class="col-3 m-1 form-control" asp-for="Description">Описание</label>
                    <label class="col-3 m-1 form-control" asp-for="Location">Местоположение</label>
                </div>
                <div class=" form-group row">
                    <input class="col-2  form-control m-1" asp-for="Id" disabled />
                    <input class="col-3  form-control m-1" asp-for="ItemName" />
                    <input class="col-3  form-control m-1" asp-for="Description" />
                    <input class="col-3  form-control m-1" asp-for="Location" />
                </div>
                <div class=" form-group row">
                    <button type="submit" class="col-3 btn btn-success m-1">Запазване</button>
                    <button asp-action="Index" class="col-3 btn btn-danger m-1">Назад</button>
                </div>
            </div>
        </div>
    </form>
</body>

InventoryStorage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryStorage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-toggler navbar-expand-sm navbar-fixed-top navbar-toggleable-sm navbar-light border-bottom box-shadow mb-md-2"
             style="background-color: #24A19C; text-emphasis-color: white; ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:whitesmoke;font-size:x-large;">InventoryStorage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" >
                            <a class="nav-link " asp-area="" asp-controller="Item" asp-action="Index" style="color: whitesmoke; font-size: medium; font-family: 'Arial Rounded MT'; ">Таблица с предмети      </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Search" asp-action="Index" style="color: whitesmoke; font-size: medium; font-family: 'Arial Rounded MT'; ">Търсене</a>
                        </li><li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="History" asp-action="Index" style="color: whitesmoke; font-size: medium; font-family:'Arial Rounded MT'; ">История на предмети</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InventoryStorage 
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>